# Beginner's Guide to ETL (Extract, Transform, Load)

Before we start, let's create a sample `messy_sales_data.csv` file. This is the raw data we will work with.

In [31]:
#Q1: What are the three stages of ETL? Describe each stage using an example from today's sales dataset

import pandas as pd
df_raw_sample.to_csv('/content/messy_sales_data.csv', index=False)
print("Sample 'messy_sales_data.csv' created successfully!")

Sample 'messy_sales_data.csv' created successfully!

### Stage 1: EXTRACT
This is about getting data from its source.

In [32]:
import pandas as pd
df_sales_raw = pd.read_csv('/content/messy_sales_data.csv')
df_sales_raw.head()

,order_id,customer_name,Product Name,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

### Stage 2: TRANSFORM
This is where we clean and change the data.

In [33]:
df_sales_transformed = df_sales_raw.copy()
df_sales_transformed.columns = df_sales_transformed.columns.str.lower().str.replace(' ', '_').str.replace('"', '')
df_sales_transformed.rename(columns={'product_name': 'product', 'order_date': 'date'}, inplace=True)
df_sales_transformed['date'] = pd.to_datetime(df_sales_transformed['date'], errors='coerce')
df_sales_transformed['quantity'].fillna(0, inplace=True)
df_sales_transformed['unit_price'].fillna(df_sales_transformed['unit_price'].median(), inplace=True)
df_sales_transformed['total_sale_amount'] = df_sales_transformed['quantity'] * df_sales_transformed['unit_price']
df_sales_transformed.head()

/tmp/ipykernel_695/3401099992.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sales_transformed['quantity'].fillna(0, inplace=True)
/tmp/ipykernel_695/3401099992.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sales_transformed['unit_price'].fillna(df_sales_transformed['unit_price'].median(), inplace=True)

,order_id,customer_name,product,category,quantity,unit_price,date,city,sales_rep,total_sale_amount
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma,90000.0
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao,15000.0
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma,3600.0
3,1004,Sunita Patel,Monitor,Electronics,0.0,22000,2024-01-10,Chennai,Ravi Kumar,0.0
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma,90000.0

### Stage 3: LOAD
This is saving the cleaned data.

In [34]:
output_file_path = '/content/cleaned_sales_data.csv'
df_sales_transformed.to_csv(output_file_path, index=False)
print(f"Cleaned data saved to '{output_file_path}'")
df_loaded = pd.read_csv(output_file_path)
df_loaded.head()

Cleaned data saved to '/content/cleaned_sales_data.csv'

,order_id,customer_name,product,category,quantity,unit_price,date,city,sales_rep,total_sale_amount
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma,90000.0
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao,15000.0
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma,3600.0
3,1004,Sunita Patel,Monitor,Electronics,0.0,22000,2024-01-10,Chennai,Ravi Kumar,0.0
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma,90000.0

In [35]:
import pandas as pd
df_sales_raw = pd.DataFrame(raw_data)

print("--- ETL Stage 1: EXTRACT ---")
print(df_sales_raw.head())
df_sales_raw.info()

print("\n--- ETL Stage 2: TRANSFORM ---")
df_sales_transformed = df_sales_raw.copy()
df_sales_transformed.columns = df_sales_transformed.columns.str.lower().str.replace(' ', '_').str.replace('"', '')
df_sales_transformed.rename(columns={'product_name': 'product', 'order_date': 'date'}, inplace=True)
df_sales_transformed['date'] = pd.to_datetime(df_sales_transformed['date'], errors='coerce')
df_sales_transformed.dropna(subset=['product', 'date'], inplace=True)
df_sales_transformed['quantity'].fillna(0, inplace=True)
df_sales_transformed['unit_price'].fillna(df_sales_transformed['unit_price'].median(), inplace=True)
df_sales_transformed['quantity'] = pd.to_numeric(df_sales_transformed['quantity'], errors='coerce').fillna(0)
df_sales_transformed['unit_price'] = pd.to_numeric(df_sales_transformed['unit_price'], errors='coerce').fillna(0)
df_sales_transformed['total_sale_amount'] = df_sales_transformed['quantity'] * df_sales_transformed['unit_price']
print(df_sales_transformed[['quantity', 'unit_price', 'total_sale_amount']].head())
daily_sales = df_sales_transformed.groupby('date')['total_sale_amount'].sum().reset_index()
print(daily_sales.head())

df_sales_transformed.info()
print(df_sales_transformed.head())
print("\n--- ETL Stage 3: LOAD ---")
output_file_path = '/content/cleaned_sales_data.csv'
df_sales_transformed.to_csv(output_file_path, index=False)
print(f"Data saved to '{output_file_path}'")
df_loaded = pd.read_csv(output_file_path)
print(df_loaded.head())
df_loaded.info()

--- ETL Stage 1: EXTRACT ---
   order_id customer_name Product Name     category  quantity  unit_price  \
0      1001  Ramesh Kumar       Laptop  Electronics       2.0       45000
1      1002    Priya Nair          NaN  Electronics       1.0       15000
2      1003    AMIT VERMA     Keyboard  Accessories       3.0        1200
3      1004  Sunita Patel      Monitor  Electronics       NaN       22000
4      1005  Ramesh Kumar       Laptop  Electronics       2.0       45000

   order_date       city    sales_rep
0  2024-01-05     Mumbai  Anil Sharma
1  2024-01-07      Delhi   Sunita Rao
2  2024-01-08  Bangalore  Anil Sharma
3  2024-01-10    Chennai   Ravi Kumar
4  2024-01-05     Mumbai  Anil Sharma
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5 non-null      int64
 1   customer_name  5 non-null      object
 2   Product Name   5 non-null      object
 3   category       5 non-null      object
 4   quantity       4 non-null      float64
 5   unit_price     5 non-null      int64
 6   order_date     5 non-null      object
 7   city           5 non-null      object
 8   sales_rep      5 non-null      object
dtypes: float64(1), int64(2), object(6)
memory usage: 492.0+ bytes

--- ETL Stage 2: TRANSFORM ---
   quantity  unit_price  total_sale_amount
0       2.0       45000            90000.0
1       1.0       15000            15000.0
2       3.0        1200             3600.0
3       0.0       22000                0.0
4       2.0       45000            90000.0
        date  total_sale_amount
0 2024-01-05           180000.0
1 2024-01-07            15000.0
2 2024-01-08             3600.0
3 2024-01-10                0.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           5 non-null      int64
 1   customer_name      5 non-null      object
 2   product            5 non-null      object
 3   category           5 non-null      object
 4   quantity           5 non-null      float64
 5   unit_price         5 non-null      int64
 6   date               5 non-null      datetime64[ns]
 7   city               5 non-null      object
 8   sales_rep          5 non-null      object
 9   total_sale_amount  5 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 532.0+ bytes
   order_id customer_name   product     category  quantity  unit_price  \
0      1001  Ramesh Kumar    Laptop  Electronics       2.0       45000
1      1002    Priya Nair       NaN  Electronics       1.0       15000
2      1003    AMIT VERMA  Keyboard  Accessories       3.0        1200
3      1004  Sunita Patel   Monitor  Electronics       0.0       22000
4      1005  Ramesh Kumar    Laptop  Electronics       2.0       45000

        date       city    sales_rep  total_sale_amount
0 2024-01-05     Mumbai  Anil Sharma            90000.0
1 2024-01-07      Delhi   Sunita Rao            15000.0
2 2024-01-08  Bangalore  Anil Sharma             3600.0
3 2024-01-10    Chennai   Ravi Kumar                0.0
4 2024-01-05     Mumbai  Anil Sharma            90000.0

--- ETL Stage 3: LOAD ---
Data saved to '/content/cleaned_sales_data.csv'
   order_id customer_name   product     category  quantity  unit_price  \
0      1001  Ramesh Kumar    Laptop  Electronics       2.0       45000
1      1002    Priya Nair       NaN  Electronics       1.0       15000
2      1003    AMIT VERMA  Keyboard  Accessories       3.0        1200
3      1004  Sunita Patel   Monitor  Electronics       0.0       22000
4      1005  Ramesh Kumar    Laptop  Electronics       2.0       45000

         date       city    sales_rep  total_sale_amount
0  2024-01-05     Mumbai  Anil Sharma            90000.0
1  2024-01-07      Delhi   Sunita Rao            15000.0
2  2024-01-08  Bangalore  Anil Sharma             3600.0
3  2024-01-10    Chennai   Ravi Kumar                0.0
4  2024-01-05     Mumbai  Anil Sharma            90000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           5 non-null      int64
 1   customer_name      5 non-null      object
 2   product            4 non-null      object
 3   category           5 non-null      object
 4   quantity           5 non-null      float64
 5   unit_price         5 non-null      int64
 6   date               5 non-null      object
 7   city               5 non-null      object
 8   sales_rep          5 non-null      object
 9   total_sale_amount  5 non-null      float64
dtypes: float64(2), int64(2), object(6)
memory usage: 532.0+ bytes

/tmp/ipykernel_695/1254843146.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sales_transformed['quantity'].fillna(0, inplace=True)
/tmp/ipykernel_695/1254843146.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sales_transformed['unit_price'].fillna(df_sales_transformed['unit_price'].median(), inplace=True)

In [36]:
#A DataFrame has 500 rows. After calling df.dropna(), it has 412 rows. What does this tell you?
import pandas as pd
import numpy as np

df_example = pd.DataFrame({
    'col1': [1, 2, 3, np.nan, 5, 6, 7, np.nan, 9, 10],
    'col2': ['A', 'B', np.nan, 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'col3': [True, False, True, False, True, False, True, True, np.nan, False]
})

initial_rows = 500
rows_with_nans_to_drop = 88



print(f"Initial rows: {initial_rows}")
print(f"Rows after df.dropna(): {initial_rows - rows_with_nans_to_drop}")
print(f"This tells us that {rows_with_nans_to_drop} rows contained at least one NaN value and were removed by the dropna() operation.")

Initial rows: 500
Rows after df.dropna(): 412
This tells us that 88 rows contained at least one NaN value and were removed by the dropna() operation.

In [37]:
#Q3: Write code to remove duplicates from df where 'same row' means same customer_name AND same product.
df_no_duplicates = df_sales_transformed.drop_duplicates(subset=['customer_name', 'product'])
print("DataFrame after removing duplicates:")
print(df_no_duplicates.head())

DataFrame after removing duplicates:
   order_id customer_name   product     category  quantity  unit_price  \
0      1001  Ramesh Kumar    Laptop  Electronics       2.0       45000
1      1002    Priya Nair       NaN  Electronics       1.0       15000
2      1003    AMIT VERMA  Keyboard  Accessories       3.0        1200
3      1004  Sunita Patel   Monitor  Electronics       0.0       22000

        date       city    sales_rep  total_sale_amount
0 2024-01-05     Mumbai  Anil Sharma            90000.0
1 2024-01-07      Delhi   Sunita Rao            15000.0
2 2024-01-08  Bangalore  Anil Sharma             3600.0
3 2024-01-10    Chennai   Ravi Kumar                0.0

In [38]:
#Q4: What is the difference between fillna(e) and fillna(df['col'].median()) ? When would you prefer each?
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'numerical_col': [10, 20, np.nan, 40, 50, np.nan, 70],
    'categorical_col': ['A', 'B', 'C', np.nan, 'E', 'F', np.nan]
})

print("Original DataFrame:\n", df)

# fillna(e) - filling with a static value
df_filled_static = df.copy()
df_filled_static['numerical_col'] = df_filled_static['numerical_col'].fillna(0)
df_filled_static['categorical_col'] = df_filled_static['categorical_col'].fillna('UNKNOWN')
print("\nDataFrame after fillna(e) with static values (0 for numerical, 'UNKNOWN' for categorical):\n", df_filled_static)
print("Use fillna(e) when you have a specific, predetermined value to replace missing data, like a default or a sentinel value.")

# fillna(df['col'].median()) - filling with a statistical measure
df_filled_median = df.copy()
median_val = df_filled_median['numerical_col'].median()
df_filled_median['numerical_col'] = df_filled_median['numerical_col'].fillna(median_val)
print(f"\nDataFrame after fillna(df['col'].median()) for numerical_col (median={median_val}):\n", df_filled_median)
print("Use fillna(df['col'].median()) (or mean/mode) when imputing missing numerical data with a central tendency measure from the data itself. Median is preferred over mean when data might have outliers.")

Original DataFrame:
    numerical_col categorical_col
0           10.0               A
1           20.0               B
2            NaN               C
3           40.0             NaN
4           50.0               E
5            NaN               F
6           70.0             NaN

DataFrame after fillna(e) with static values (0 for numerical, 'UNKNOWN' for categorical):
    numerical_col categorical_col
0           10.0               A
1           20.0               B
2            0.0               C
3           40.0         UNKNOWN
4           50.0               E
5            0.0               F
6           70.0         UNKNOWN
Use fillna(e) when you have a specific, predetermined value to replace missing data, like a default or a sentinel value.

DataFrame after fillna(df['col'].median()) for numerical_col (median=40.0):
    numerical_col categorical_col
0           10.0               A
1           20.0               B
2           40.0               C
3           40.0             NaN
4           50.0               E
5           40.0               F
6           70.0             NaN
Use fillna(df['col'].median()) (or mean/mode) when imputing missing numerical data with a central tendency measure from the data itself. Median is preferred over mean when data might have outliers.

In [ ]:
#Q5: Write Python code to call the weather API for 'Delhi' and print the temperature in Celsius.
import requests

api_key = "a90ece615d6beed52df4e2e676335810"
city = "Delhi"

url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

response =  requests.get(url)

print("Status Code:", response.status_code)

if response.status_code == 200:

    data = response.json()

    print("City:", data["name"])
    print("Temperature:", data["main"]["temp"], "°C")
    print("Weather:", data["weather"][0]["description"])

else:

    print("Error:", response.text)

Status Code: 200
City: Delhi
Temperature: 39.05 °C
Weather: haze