In [1]:
# Running locally - CSV file is already in the same folder

In [2]:
import pandas as pd
df = pd.read_csv('student_performance.csv')
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [3]:
import pandas as pd
df = pd.read_csv('student_performance.csv')
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [4]:
import pandas as pd
df = pd.read_csv('student_performance.csv')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(df)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [5]:
import pandas as pd
data = pd.read_csv("student_performance.csv")
print(data)
data = data.drop([0,1,2,3,4])
print(data)
data.to_csv("new_file.csv",index=False)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023
    student_id            name  age  gender        department  semester  \
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [6]:
data = pd.read_csv("student_performance.csv")
print(data)
data = data.drop([0,1,2,3,4])
print(data)
data.to_csv("updatedfile(Aman).csv",index=False)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023
    student_id            name  age  gender        department  semester  \
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [7]:
import pandas as pd
data = pd.read_csv("student_performance.csv")
print(data)
mathscore = 85
result = data[data["math_score"] == mathscore]
print(result)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023
   student_id          name  age gender        department  semester  \
0        1001  Aarav Sharma   19   Male  Computer Science         2

   math_score  science_score  english_score  programming_score  \
0          85             78             72                 91

   attendance_percentage    city  admission_year
0                     92  Mumbai            2023

In [8]:
print("department in the Given data set:")
print(df['department'].unique())
print("\n How many studnet per department:")
print(df['department'].value_counts())

department in the Given data set:
<StringArray>
['Computer Science', 'Electronics', 'Mechanical', 'Civil']
Length: 4, dtype: str

 How many studnet per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [9]:
print("Gender in the Given data set:")
print(df['gender'].unique())
print("\n How many studnet per Gender:")
print(df['gender'].value_counts())

Gender in the Given data set:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

 How many studnet per Gender:
gender
Male      15
Female    15
Name: count, dtype: int64

In [10]:
print("semester in the Given data set:")
print(df['semester'].unique())
print("\n How many studnet per semester:")
print(df['semester'].value_counts())

semester in the Given data set:
[2]

 How many studnet per semester:
semester
2    30
Name: count, dtype: int64

In [11]:
print("City in the Given data set:")
print(df['city'].unique())
print("\n How many studnet per city:")
print(df['city'].value_counts())

City in the Given data set:
<StringArray>
[            'Mumbai',          'Ahmedabad',              'Delhi',
          'Hyderabad',              'Kochi',               'Pune',
          'Bangalore',            'Lucknow',           'Varanasi',
            'Kolkata',            'Chennai',             'Jaipur',
             'Mysore',           'Thrissur',             'Bhopal',
               'Agra',              'Patna',             'Nagpur',
           'Dehradun',         'Chandigarh', 'Thiruvananthapuram',
              'Surat',          'Allahabad',             'Kanpur',
             'Indore']
Length: 25, dtype: str

 How many studnet per city:
city
Kochi                 2
Lucknow               2
Kolkata               2
Agra                  2
Thiruvananthapuram    2
Mumbai                1
Ahmedabad             1
Delhi                 1
Hyderabad             1
Pune                  1
Bangalore             1
Varanasi              1
Chennai               1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [12]:
cs_student=df[(df['city']=='Mumbai')|(df['city']=='Delhi')]
print(cs_student[['name','city','programming_score']])

           name    city  programming_score
0  Aarav Sharma  Mumbai                 91
2   Rohit Verma   Delhi                 55

In [13]:
high_attendce=df[df['attendance_percentage'] > 90]
print(f"Students with attendance greater than 90:")
print(high_attendce[['name','department','attendance_percentage']])

Students with attendance greater than 90:
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [14]:
high_attendce=df[df['attendance_percentage'] < 90]
print(f"Students with attendance lessar than 90:")
print(high_attendce[['name','department','attendance_percentage']])

Students with attendance lessar than 90:
              name        department  attendance_percentage
1      Priya Patel  Computer Science                     87
2      Rohit Verma       Electronics                     78
5      Meera Joshi       Electronics                     72
6      Kiran Kumar             Civil                     85
8     Rahul Mishra        Mechanical                     68
10     Vikram Iyer       Electronics                     83
11     Pooja Gupta             Civil                     80
12      Suresh Rao  Computer Science                     88
14     Ajay Tiwari  Computer Science                     75
16    Manoj Pandey             Civil                     65
18  Deepak Chauhan        Mechanical                     77
19    Nisha Kapoor  Computer Science                     89
20   Harish Pillai       Electronics                     74
22    Sanjay Dubey             Civil                     70
23   Preeti Saxena        Mechanical                     86
25      Rekha Nair       Electronics                     82
26   Gaurav Shukla  Computer Science                     87
27   Sunita Pillai             Civil                     73
28      Nitin Jain        Mechanical                     84

In [15]:
df['average_score'] = df[['math_score', 'science_score', 'english_score', 'programming_score']].mean(axis=1)
lowest_performing_student = df.loc[df['average_score'].idxmin()]
print("Lowest Performing Student:")
print(f"Name: {lowest_performing_student['name']}")
print(f"Age: {lowest_performing_student['age']}")
print(f"Gender: {lowest_performing_student['gender']}")
print(f"Department: {lowest_performing_student['department']}")
print(f"Average Score: {lowest_performing_student['average_score']:.2f}")

Lowest Performing Student:
Name: Manoj Pandey
Age: 21
Gender: Male
Department: Civil
Average Score: 52.50